#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidClient.Resource", IsApplication=true)]

namespace AndroidClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::AndroidClient.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::AndroidClient.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::AndroidClient.Resource.String.ApplicationName;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cell_header = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cell_value = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080032
			public const int Main = 2131230770;
			
			// aapt resource value: 0x7f08002c
			public const int SubscriptionDetails = 2131230764;
			
			// aapt resource value: 0x7f08003f
			public const int action_settings = 2131230783;
			
			// aapt resource value: 0x7f08003e
			public const int agentWebView = 2131230782;
			
			// aapt resource value: 0x7f08003d
			public const int barChart1 = 2131230781;
			
			// aapt resource value: 0x7f080000
			public const int btnCancel = 2131230720;
			
			// aapt resource value: 0x7f08002d
			public const int buttonDefault = 2131230765;
			
			// aapt resource value: 0x7f08002f
			public const int buttonThree = 2131230767;
			
			// aapt resource value: 0x7f08002e
			public const int buttonTwo = 2131230766;
			
			// aapt resource value: 0x7f080020
			public const int currencygrp = 2131230752;
			
			// aapt resource value: 0x7f08003a
			public const int dailyBarChart = 2131230778;
			
			// aapt resource value: 0x7f080021
			public const int dollar = 2131230753;
			
			// aapt resource value: 0x7f080031
			public const int framecontent = 2131230769;
			
			// aapt resource value: 0x7f080034
			public const int gvCtrl = 2131230772;
			
			// aapt resource value: 0x7f080022
			public const int inr = 2131230754;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080025
			public const int linearLayout12 = 2131230757;
			
			// aapt resource value: 0x7f080012
			public const int linearLayout2 = 2131230738;
			
			// aapt resource value: 0x7f080024
			public const int loginBtn = 2131230756;
			
			// aapt resource value: 0x7f080018
			public const int monthlyGVCtrl = 2131230744;
			
			// aapt resource value: 0x7f08001f
			public const int myRadioGroup = 2131230751;
			
			// aapt resource value: 0x7f08001d
			public const int passwordET = 2131230749;
			
			// aapt resource value: 0x7f080030
			public const int progressBar = 2131230768;
			
			// aapt resource value: 0x7f080016
			public const int regionGVCtrl = 2131230742;
			
			// aapt resource value: 0x7f080005
			public const int relativeLayout1 = 2131230725;
			
			// aapt resource value: 0x7f080017
			public const int resourcesGVCtrl = 2131230743;
			
			// aapt resource value: 0x7f080037
			public const int rootLayout = 2131230775;
			
			// aapt resource value: 0x7f08003c
			public const int selectedBar = 2131230780;
			
			// aapt resource value: 0x7f080039
			public const int selectedBarDay = 2131230777;
			
			// aapt resource value: 0x7f08003b
			public const int selectedMeterCategory = 2131230779;
			
			// aapt resource value: 0x7f080038
			public const int selectedMonth = 2131230776;
			
			// aapt resource value: 0x7f080006
			public const int tableLayout1 = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int tableRow1 = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int tableRow2 = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int tableRow3 = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int tableRow4 = 2131230736;
			
			// aapt resource value: 0x7f080019
			public const int textView1 = 2131230745;
			
			// aapt resource value: 0x7f08000b
			public const int textView12 = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int textView14 = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int textView15 = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int textView16 = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int textView17 = 2131230741;
			
			// aapt resource value: 0x7f08001a
			public const int textView2 = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int textView3 = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int textView4 = 2131230750;
			
			// aapt resource value: 0x7f080014
			public const int top5GVCtrl = 2131230740;
			
			// aapt resource value: 0x7f08002b
			public const int txtCost = 2131230763;
			
			// aapt resource value: 0x7f080027
			public const int txtMonthCost = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int txtMonthName = 2131230758;
			
			// aapt resource value: 0x7f080029
			public const int txtRegionCost = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int txtRegionName = 2131230760;
			
			// aapt resource value: 0x7f08002a
			public const int txtResourceName = 2131230762;
			
			// aapt resource value: 0x7f080036
			public const int txtServiceCost = 2131230774;
			
			// aapt resource value: 0x7f080035
			public const int txtServiceName = 2131230773;
			
			// aapt resource value: 0x7f080004
			public const int txtSubId = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int txtSubName = 2131230723;
			
			// aapt resource value: 0x7f080023
			public const int txterror = 2131230755;
			
			// aapt resource value: 0x7f080033
			public const int txtloginas = 2131230771;
			
			// aapt resource value: 0x7f08000f
			public const int txtselectedsubavg = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int txtselectedsubcost = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int txtselectedsubname = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int txtvw10 = 2131230728;
			
			// aapt resource value: 0x7f08001b
			public const int usernameET = 2131230747;
			
			// aapt resource value: 0x7f080001
			public const int webView1 = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_authentication = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int custGridViewItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FrameLayoutDefault = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FrameLayoutOne = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FrameLayoutThree = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int monthlyGridView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int regionGridView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int resourcesGridView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SubscriptionDetails = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Subscriptions = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int top5GridView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int UsageByDayChart = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int UsageByResourceChart = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int WebAuthenticationBroker = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int authentication = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int login = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int token = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000f
			public const int Hello = 2130968591;
			
			// aapt resource value: 0x7f040003
			public const int action_settings = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int app_loading = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f04000d
			public const int broker_authentication_request_is_invalid = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int broker_processing = 2130968590;
			
			// aapt resource value: 0x7f040005
			public const int button_cancel = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int confirmation_activity_authentication = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int default_not_supported_msg = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int error_token_type_not_supported = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int hello_world = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int title_activity_authentication = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int title_activity_login = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int title_activity_token = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int title_confirmation_activity_authentication = 2130968585;
			
			// aapt resource value: 0x7f040010
			public const int title_login_hello_app = 2130968592;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CodeFont = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Mono_Android_Theme_Splash = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
